---
language: ruby
dist: xenial
bundler_args: --without development system_tests
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
matrix:
  include:
    fast_finish: true
  include:
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
